smicyk/groovy-jmeter

src/groovydoc/resources/overview-summary.html, src/main/groovy/net/simonix/dsl/jmeter/factory/assertion/CheckFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/common/ArgumentsFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/common/ParamsFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/config/VariablesFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/extractor/CssSelectorExtractorFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/extractor/JsonPathExtractorFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/extractor/RegExExtractorFactory.groovy
=> [change] - update groovydoc overview page, minor updates to comments in the code

README.MD, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/BaseHttpFactory.groovy, src/test/groovy/net/simonix/dsl/jmeter/HttpSamplerSpec.groovy
- when using short version for HTTP sampler some of the URLS doesn't produce proper test element configuration
- improve documentation
=> [fix] - fix parsing of urls for HTTP sampler

examples/README.MD, examples/jsr223/groovy/postprocessor.groovy, examples/jsr223/groovy/preprocessor.groovy, examples/jsr223/groovy/sampler.groovy, examples/jsr223/run.sh, examples/jsr223/script.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/AbstractJSR223Factory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/DslDefinition.groovy, src/test/groovy/net/simonix/dsl/jmeter/ExecuteControllersSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/ExecutionControllersSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/FactoryBuilderSpec.groovy, src/test/resources/net/simonix/dsl/jmeter/csv_0.jmx
- small changes in jsr223 properties
- changes in csv required properties
=> [change] - add example for jsr223 test elements

README.MD, examples/application/script.groovy, examples/commandline/script.groovy, examples/docker-gradle/scripts/script.groovy, examples/docker/script.groovy, examples/gradle/scripts/script.groovy, examples/jsr223/script.groovy, examples/standalone/script.groovy, examples/structure/script.groovy, src/main/groovy/idesupport/jmeter.gdsl, src/main/groovy/net/simonix/dsl/jmeter/factory/AbstractTestElementFragmentFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/common/BodyFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/common/InsertFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/config/CsvDataFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/controller/IncludeFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/listener/AggregateFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/listener/SummaryFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/DslDefinition.groovy, src/test/groovy/net/simonix/dsl/jmeter/FactoryBuilderSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/InsertFactorySpec.groovy
- always when input is from file the property keyword is named 'file'
=> [change] - make file property usage consistent

src/main/groovy/net/simonix/dsl/jmeter/factory/assertion/JsonAssertionFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/FlowControlActionFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/timer/ConstantTimerFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/timer/UniformRandomTimeFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/DslDefinition.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/Constraints.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/InListPropertyConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/PropertyConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/RangePropertyConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/validation/PropertyValidator.groovy, src/main/groovy/net/simonix/dsl/jmeter/validation/RequiredOnlyValidator.groovy, src/main/groovy/net/simonix/dsl/jmeter/validation/ValidationResult.groovy, src/test/groovy/net/simonix/dsl/jmeter/FactoryBuilderSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/validation/PropertyValidatorSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/validation/RequiredValidatorSpec.groovy
- possibility to define constraints for dsl property
- two new constraints list and range
- minor javadoc fixes
- make consistent property naming for jsonassertion
=> [change] - add property constraints

README.MD, examples/README.MD, src/main/groovy/net/simonix/dsl/jmeter/builder/JdbcFactoryBuilder.groovy
- update jdbc builder to include other keywords for timers, preprocessors, postprocessors and assertions
=> [feature] - update documentation with jdbc information

src/main/groovy/net/simonix/dsl/jmeter/TestScriptRunner.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/TestElementNodeFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/BaseHttpFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/statistics/Statistics.groovy, src/main/groovy/net/simonix/dsl/jmeter/statistics/StatisticsListener.groovy, src/main/groovy/net/simonix/dsl/jmeter/statistics/StatisticsProvider.groovy, src/test/groovy/net/simonix/dsl/jmeter/HttpSamplerSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/StatisticsSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/test/spec/TempFileSpec.groovy
- some basic statistics can be calculated to check in junit assersions
- better jmx file generation checking
- name property takes precedence when setting test element name
=> [feature] - add basic statistics calculations for junit test

examples/README.MD, examples/distributed/docker-compose.yml, examples/distributed/run.bat, examples/distributed/run.sh, examples/distributed/script.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScript.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScriptBase.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScriptServerRunner.groovy
- new example with docker setup for distributed testing
=> [feature] - add distributed testing feature from JMeter

examples/commandline/run.sh, examples/commandline/script.groovy
Thank you @smicyk for all helps you gave me when I was trying to get things working. 
As a token of my appreciation, I did some  minor enhancements to the `commandline` script, which hopefully can be a bit more clearer to the next person who picks up from it afresh. 
Thanks
=> minor enhance

src/main/groovy/net/simonix/dsl/jmeter/builder/AjpFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/DefaultFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/GraphQLFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/HttpFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/JdbcFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/assertion/JMESAssertionFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/assertion/XPathAssertionFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/extractor/JMESPathExtractorFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/resources/net/simonix/dsl/jmeter/model/definition/messages.properties, src/test/groovy/net/simonix/dsl/jmeter/factory/assertion/AssertionFactorySpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/extractor/ExtractorFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_1.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/extractor/extractors_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/extractor/extractors_1.jmx
Fixes #56 
- new test elements
- assert and extract for xpath, jpath, jmes has consistent naming for expression value
=> [feature] - add jmes extractor and assertion

src/groovydoc/resources/overview-summary.html, src/main/groovy/idesupport/jmeter.gdsl, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DefinitionBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy
- update gdsl and groovydoc overview summary
=> [feature] - keep dsl properties sorted in DslDefinition

src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/resources/net/simonix/dsl/jmeter/model/definition/messages.properties, src/test/groovy/net/simonix/dsl/jmeter/factory/listener/ListenerFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/listener/listeners_1.jmx
- the view keyword doesn't require file by default
- the view keyword default name is View Result Tree
Fixing #72
=> [feature] - update default values for view keyword

src/main/groovy/net/simonix/dsl/jmeter/factory/group/GroupFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/group/PostGroupFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/group/PreGroupFactory.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/group/GroupFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/group/group_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/group/group_2.jmx
- duration and delay were mixed, and now they are properly set
=> [fix] - fix mixed group parameters

src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/DebugFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/sampler/DebugSamplerSpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/sampler/debug_0.jmx
- all values for debug sampler was not saved during jmx out operation
=> [fix] - debug properties not saved to jmx file

examples/.gitignore, examples/plugins/dummy_plugin.jmx, examples/plugins/run.bat, examples/plugins/run.sh, examples/plugins/script.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScriptBase.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScriptRunner.groovy, src/main/groovy/net/simonix/dsl/jmeter/utils/JMeterCompatibility.groovy, src/main/resources/org/apache/jmeter/upgrade.properties
- fixing include keyword to run any JMX code with groovy-jmeter (including external plugins)
- add new upgrade.properties as default properties file
=> [fix] - running plugins with include element

src/main/groovy/net/simonix/dsl/jmeter/FragmentTestScript.groovy, src/main/groovy/net/simonix/dsl/jmeter/TestScriptRunner.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/AjpFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/BackendFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/DefaultsHttpFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/GraphQLFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/HttpFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/JdbcFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/AbstractTestElementFragmentFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/TestElementNode.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/common/InsertFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/common/insert_1.jmx, src/test/resources/net/simonix/dsl/jmeter/fragments/arguments.groovy, src/test/resources/net/simonix/dsl/jmeter/fragments/multiple.groovy, src/test/resources/net/simonix/dsl/jmeter/fragments/params.groovy
- the fragment can have multiple root elements and can be applied on all levels of test tree
=> [feature] - improve insert keyword

build.gradle, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/Constraints.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/InListPropertyConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/NotEmptyContraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/NotNullConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/constraint/RangePropertyConstraint.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/groovy/net/simonix/dsl/jmeter/validation/PropertyValidator.groovy, src/main/groovy/net/simonix/dsl/jmeter/validation/RequiredOnlyValidator.groovy, src/test/groovy/net/simonix/dsl/jmeter/validation/RequiredValidatorSpec.groovy
- new constraints notNull and notEmpty
- if required and default set the validator pass
=> [feature] - add new constrains and new behaviour for default value are reuiqred

examples/java-request/JavaRequestTest.groovy, examples/java-request/run.bat, examples/java-request/run.sh, examples/java-request/script.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/DefaultFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/JavaRequestFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/java/JavaRequestArgumentFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/java/JavaRequestArgumentsFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/sampler/java/JavaRequestFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/resources/net/simonix/dsl/jmeter/model/definition/messages.properties, src/test/groovy/net/simonix/dsl/jmeter/factory/sampler/DebugSamplerSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/sampler/JavaRequestFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/sampler/java_0.jmx
- new sampler to execute java_request
- example how to create own java request (with groovy script)
=> [feature] - add java request sampler

src/main/groovy/net/simonix/dsl/jmeter/builder/DefaultFactoryBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/builder/TestTreeBuilder.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/controller/raw/IncludeRawFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/controller/raw/IncludeRawTestElement.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/resources/net/simonix/dsl/jmeter/model/definition/messages.properties, src/test/groovy/net/simonix/dsl/jmeter/factory/controller/ControllerFactorySpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/test/spec/TempFileSpec.groovy
- feature gives possibility to add jmx to the groovy file - it gives a way to include features which are not yet available groovy-jmeter or to add plugins
=> [feature] - add support to include raw jmx file content to the script

src/main/groovy/net/simonix/dsl/jmeter/factory/controller/LoopFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/group/GroupFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/group/PostGroupFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/factory/group/PreGroupFactory.groovy, src/main/groovy/net/simonix/dsl/jmeter/model/definition/DslDefinition.groovy, src/main/groovy/net/simonix/dsl/jmeter/utils/LoopControllerUtils.groovy, src/test/groovy/net/simonix/dsl/jmeter/StatisticsSpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/controller/ControllerFactorySpec.groovy, src/test/groovy/net/simonix/dsl/jmeter/factory/group/GroupFactorySpec.groovy, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_1.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_2.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/assertion/assertions_3.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/common/insert_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/common/insert_1.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/common/shorts_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/config/jdbc_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/controller/controllers_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/controller/controllers_1.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/controller/controllers_2.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/group/group_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/group/group_2.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/group/group_4.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/jsr/jsr_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/postprocessor/debug_1.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/sampler/debug_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/sampler/graphql_0.jmx, src/test/resources/net/simonix/dsl/jmeter/factory/sampler/java_0.jmx
- the forever parameter now works same as in jmeter gui, it overrides the number of loops in user group and loop controller making it infinite
=> [bugfix] - fixing forever parameter handling in group and loop elements
